### PR TITLE
Update Area.cs

### PR DESCRIPTION
**Pull request by eriksimonic**
Added function WaitAny works great

### CODE REVIEW

**Comment by quellatalo** [comment]
There's a `try` with no `catch`. Would it be better to not use any `try` at all, and let the package user see which pattern is making the error?

**Comment by eriksimonic** [comment]
Hey.
I used the pattern to stop the stopwatch, the user will still get the exception as it is intended. 
this _is_ somehow similar to using(var st = MyStopWatch()) ..

in the case that the recognition throws an error, the stopwatch will run till, the GC will collect it. 
Clearification.
https://stackoverflow.com/questions/4305753/will-try-finally-without-the-catch-bubble-the-exception

**Comment by quellatalo** [comment]
Oh hi,
Actually, the stopwatch doesn't work like a thread. There's nothing running. (Even though the `StartNew` naming can cause some misleading)
https://stackoverflow.com/questions/24140261/should-i-stop-stopwatch-at-the-end-of-the-method
And, the source of StopWatch: http://referencesource.microsoft.com/#System/services/monitoring/system/diagnosticts/Stopwatch.cs

**Comment by eriksimonic** [comment]
My mistake big time.. 
I will correct and do another pull request.

**Pull request merged**
